source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target :AsyncImageFetcherDemo do
  pod 'SwiftLint', '0.39.1'
end

target :Specs do
    pod 'Quick', '2.2.0'
    pod 'Nimble', '8.0.5'
end
